spin_manifest_version = 2

[application]
name = "test-start-spin"
version = "0.2.0"
authors = ["Daniel Mantei <dan.mantei@outlook.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "test-start-spin"

[component.test-start-spin]
source = "target/wasm32-wasi/release/test_start_spin.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]

[component.test-start-spin.build]
command = "cargo leptos build --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/pkg/..."
component = "pkg"

[component.pkg]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "target/site/pkg", destination = "/" }]
